### ISSUE TITLE
Pagination switches between different pages when searching for options

### ISSUE THREAD

**Issue by Ma27** [flyingcircusio/fc-search#1]
To reproduce what I mean:

* Search for `programs`
* Go to page `15`
* Type in `php`
* Now, `flyingcircus.roles.lamp.php` is the first result (as expected).
* However, the pagination at the bottom still claims that I'm on page 15 although I see the results for page 1.
* When I hit Return now, I get forwarded to page 14 and (on fc-23.11-production from 2024-04-02 at least) the first option I see is `services.tt-rss.logDestination`).

What I'd expect is that I don't get forwarded to a different page when hitting Enter when I see different results before.
Also, I'd expect the pagination bar at the bottom to reset in the UI when typing in a new option.

**Comment by PhilTaken** [comment]
good catch, fixed in 6cb404f3dd7f89f96b27c374a05956ce5fed22b8
